using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace VuonVietKyThu {
    public sealed class UIManager : MonoBehaviour {
        public Canvas Canvas {get;private set;} public RectTransform BoardRect {get;private set;}
        SaveSystem save; LevelDatabase db; GameController game; EffectsController fx; EventSystem eventSystem; SfxPlayer sfx;
        GameObject safe,home,map,gameScreen,shop,character,events,settings,modal,toastGo;
        Text homeHearts,homeCoins,homeLevel,gameLevel,gameScore,gameMoves,gameGoals,gameFever,shopCoins,friendshipText,modalTitle,modalBody,toastText;
        Transform mapContent,shopContent,eventsContent,modalButtons; Image mapBackground; TileView[] tileViews;
        MascotMotion homeMascot,charMascot;
        readonly Color purple=new(.34f,.10f,.58f,.97f), purple2=new(.53f,.20f,.78f,.97f), gold=new(1f,.72f,.18f,1f), green=new(.18f,.78f,.26f,1f), pink=new(1f,.26f,.55f,1f), cyan=new(.12f,.70f,.91f,1f);

        public void Init(SaveSystem s,LevelDatabase d,GameController g,EffectsController e,EventSystem ev,SfxPlayer audio){save=s;db=d;game=g;fx=e;eventSystem=ev;sfx=audio;BuildCanvas();BuildHome();BuildMap();BuildGame();BuildShop();BuildCharacter();BuildEvents();BuildSettings();BuildModal();BuildToast();ShowHome();}
        void BuildCanvas(){
            var cg=UIFactory.Go("Canvas",transform);Canvas=cg.AddComponent<Canvas>();Canvas.renderMode=RenderMode.ScreenSpaceOverlay;Canvas.sortingOrder=10;var scaler=cg.AddComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(720,1280);scaler.matchWidthOrHeight=.5f;cg.AddComponent<GraphicRaycaster>();
            safe=UIFactory.Go("SafeArea",cg.transform);UIFactory.Stretch(safe);safe.AddComponent<SafeAreaFitter>();
        }
        GameObject Screen(string name,Sprite bg){var root=UIFactory.Go(name,safe.transform);UIFactory.Stretch(root);var im=root.AddComponent<Image>();im.sprite=bg;im.color=Color.white;im.preserveAspect=false;return root;}
        void TopCurrencyBar(Transform parent,out Text hearts,out Text coins){
            var p=UIFactory.Go("TopBar",parent);var rt=p.AddComponent<RectTransform>();UIFactory.Anchor(rt,new Vector2(.5f,1),new Vector2(0,-54),new Vector2(660,88));UIFactory.Panel3D(p,purple);
            hearts=UIFactory.Text("Hearts",p.transform,"♥ 5",30,TextAnchor.MiddleLeft);UIFactory.Rect(hearts.gameObject,Vector2.zero,new Vector2(.5f,1),new Vector2(28,0),new Vector2(-10,0));
            coins=UIFactory.Text("Coins",p.transform,"₫ 1.250",30,TextAnchor.MiddleRight);UIFactory.Rect(coins.gameObject,new Vector2(.5f,0),Vector2.one,new Vector2(10,0),new Vector2(-28,0));
        }
        void BuildHome(){
            home=Screen("Home",SpriteCatalog.Home());TopCurrencyBar(home.transform,out homeHearts,out homeCoins);
            var title=UIFactory.Text("Title",home.transform,"VƯỜN VIỆT\nKỲ THÚ",54,TextAnchor.MiddleCenter,new Color(.98f,.88f,.30f));var tr=title.rectTransform;UIFactory.Anchor(tr,new Vector2(.5f,1),new Vector2(0,-205),new Vector2(520,160));title.gameObject.AddComponent<Shadow>().effectDistance=new Vector2(0,-5);
            var mascotCard=UIFactory.Go("MascotCard",home.transform);var mr=mascotCard.AddComponent<RectTransform>();UIFactory.Anchor(mr,new Vector2(.34f,.5f),new Vector2(0,25),new Vector2(420,520));UIFactory.Panel3D(mascotCard,new Color(.20f,.08f,.32f,.38f));
            var mi=UIFactory.Image("Mai",mascotCard.transform,Color.white,SpriteCatalog.Mascot());UIFactory.Stretch(mi.gameObject,12,12,12,12);mi.preserveAspect=true;homeMascot=mi.gameObject.AddComponent<MascotMotion>();
            var eventCard=UIFactory.Go("EventCard",home.transform);var er=eventCard.AddComponent<RectTransform>();UIFactory.Anchor(er,new Vector2(.78f,.60f),new Vector2(-10,0),new Vector2(270,230));UIFactory.Panel3D(eventCard,new Color(.27f,.07f,.35f,.89f));var et=UIFactory.Text("Event",eventCard.transform,"SỰ KIỆN\nLễ hội Trái Cây\n\nQuà miễn phí mỗi ngày",24);UIFactory.Stretch(et.gameObject,12,12,12,12);var eb=eventCard.AddComponent<Button>();eb.targetGraphic=eventCard.GetComponent<Image>();eb.onClick.AddListener(ShowEvents);
            var play=UIFactory.Button("Play",home.transform,"CHƠI TIẾP",green,()=>game.StartLevel(save.Data.unlocked),38);UIFactory.Anchor(play.GetComponent<RectTransform>(),new Vector2(.5f,.5f),new Vector2(120,-305),new Vector2(420,112));
            homeLevel=UIFactory.Text("LevelHint",play.transform,"MÀN 1",20);UIFactory.Rect(homeLevel.gameObject,Vector2.zero,Vector2.one,new Vector2(0,-62),new Vector2(0,-14));
            var nav=UIFactory.Go("Nav",home.transform);var nr=nav.AddComponent<RectTransform>();UIFactory.Anchor(nr,new Vector2(.5f,0),new Vector2(0,76),new Vector2(670,126));var grid=nav.AddComponent<GridLayoutGroup>();grid.constraint=GridLayoutGroup.Constraint.FixedColumnCount;grid.constraintCount=5;grid.cellSize=new Vector2(126,110);grid.spacing=new Vector2(10,0);
            UIFactory.Button("Map",nav.transform,"BẢN ĐỒ",purple2,ShowMap,18);UIFactory.Button("Events",nav.transform,"SỰ KIỆN",pink,ShowEvents,18);UIFactory.Button("Character",nav.transform,"NHÂN VẬT",gold,ShowCharacter,18);UIFactory.Button("Shop",nav.transform,"CỬA HÀNG",cyan,ShowShop,18);UIFactory.Button("Settings",nav.transform,"CÀI ĐẶT",purple,ShowSettings,18);
        }
        void BuildMap(){
            map=Screen("Map",SpriteCatalog.Region(0));mapBackground=map.GetComponent<Image>();
            var header=UIFactory.Button("Back",map.transform,"‹  BẢN ĐỒ HÀNH TRÌNH",purple,ShowHome,30);UIFactory.Anchor(header.GetComponent<RectTransform>(),new Vector2(.5f,1),new Vector2(0,-58),new Vector2(650,92));
            var scroll=UIFactory.Go("Scroll",map.transform);var sr=scroll.AddComponent<RectTransform>();UIFactory.Anchor(sr,new Vector2(.5f,.5f),new Vector2(0,-20),new Vector2(650,1020));var si=scroll.AddComponent<Image>();si.color=new Color(.04f,.16f,.20f,.36f);var sc=scroll.AddComponent<ScrollRect>();sc.horizontal=false;
            var viewport=UIFactory.Go("Viewport",scroll.transform);UIFactory.Stretch(viewport);var vi=viewport.AddComponent<Image>();vi.color=new Color(1,1,1,.01f);viewport.AddComponent<Mask>().showMaskGraphic=false;sc.viewport=viewport.GetComponent<RectTransform>();
            var content=UIFactory.Go("Content",viewport.transform);var cr=content.AddComponent<RectTransform>();cr.anchorMin=new Vector2(0,1);cr.anchorMax=new Vector2(1,1);cr.pivot=new Vector2(.5f,1);cr.anchoredPosition=Vector2.zero;cr.sizeDelta=new Vector2(0,1900);var gl=content.AddComponent<GridLayoutGroup>();gl.padding=new RectOffset(18,18,20,20);gl.constraint=GridLayoutGroup.Constraint.FixedColumnCount;gl.constraintCount=4;gl.cellSize=new Vector2(142,120);gl.spacing=new Vector2(12,18);mapContent=content.transform;sc.content=cr;
        }
        void BuildGame(){
            gameScreen=Screen("Game",SpriteCatalog.Game());var top=UIFactory.Go("HUD",gameScreen.transform);var hr=top.AddComponent<RectTransform>();UIFactory.Anchor(hr,new Vector2(.5f,1),new Vector2(0,-74),new Vector2(670,120));UIFactory.Panel3D(top,purple);
            gameLevel=UIFactory.Text("Level",top.transform,"MÀN 1",27,TextAnchor.MiddleLeft);UIFactory.Rect(gameLevel.gameObject,Vector2.zero,new Vector2(.25f,1),new Vector2(20,0),Vector2.zero);
            gameScore=UIFactory.Text("Score",top.transform,"0",30);UIFactory.Rect(gameScore.gameObject,new Vector2(.25f,0),new Vector2(.72f,1),Vector2.zero,Vector2.zero);
            gameMoves=UIFactory.Text("Moves",top.transform,"30 LƯỢT",28,TextAnchor.MiddleRight);UIFactory.Rect(gameMoves.gameObject,new Vector2(.72f,0),Vector2.one,Vector2.zero,new Vector2(-18,0));
            var goals=UIFactory.Go("Goals",gameScreen.transform);var gr=goals.AddComponent<RectTransform>();UIFactory.Anchor(gr,new Vector2(.5f,1),new Vector2(0,-190),new Vector2(670,92));UIFactory.Panel3D(goals,new Color(1f,.93f,.78f,.95f));gameGoals=UIFactory.Text("GoalText",goals.transform,"MỤC TIÊU",22,TextAnchor.MiddleCenter,new Color(.27f,.08f,.32f));UIFactory.Stretch(gameGoals.gameObject,12,8,12,8);
            var fever=UIFactory.Go("Fever",gameScreen.transform);var fr=fever.AddComponent<RectTransform>();UIFactory.Anchor(fr,new Vector2(.5f,1),new Vector2(0,-258),new Vector2(630,42));UIFactory.Panel3D(fever,new Color(.13f,.05f,.22f,.85f));gameFever=UIFactory.Text("FeverText",fever.transform,"NĂNG LƯỢNG VƯỜN 0%",17);UIFactory.Stretch(gameFever.gameObject,5,0,5,0);
            var board=UIFactory.Go("Board",gameScreen.transform);BoardRect=board.AddComponent<RectTransform>();UIFactory.Anchor(BoardRect,new Vector2(.5f,.5f),new Vector2(0,-4),new Vector2(684,684));UIFactory.Panel3D(board,new Color(.04f,.26f,.49f,.94f));var grid=board.AddComponent<GridLayoutGroup>();grid.padding=new RectOffset(12,12,12,12);grid.constraint=GridLayoutGroup.Constraint.FixedColumnCount;grid.constraintCount=8;grid.cellSize=new Vector2(79,79);grid.spacing=new Vector2(4,4);tileViews=new TileView[64];for(int i=0;i<64;i++){var t=UIFactory.Go("Tile"+i,board.transform).AddComponent<TileView>();t.Build(i,game.OnTilePressed);tileViews[i]=t;}
            var boosters=UIFactory.Go("Boosters",gameScreen.transform);var br=boosters.AddComponent<RectTransform>();UIFactory.Anchor(br,new Vector2(.5f,0),new Vector2(0,106),new Vector2(670,128));var bg=boosters.AddComponent<GridLayoutGroup>();bg.constraint=GridLayoutGroup.Constraint.FixedColumnCount;bg.constraintCount=4;bg.cellSize=new Vector2(157,112);bg.spacing=new Vector2(10,0);
            UIFactory.Button("Basket",boosters.transform,"GIỎ TRE",cyan,()=>game.UseBooster("basket"),18);UIFactory.Button("Fan",boosters.transform,"QUẠT GIÓ",purple2,()=>game.UseBooster("fan"),18);UIFactory.Button("Pinwheel",boosters.transform,"CHONG CHÓNG",pink,()=>game.UseBooster("pinwheel"),17);UIFactory.Button("Pause",boosters.transform,"TẠM DỪNG",purple,()=>ShowPause(),17);
        }
        void BuildShop(){
            shop=Screen("Shop",SpriteCatalog.Home());var title=UIFactory.Button("Back",shop.transform,"‹  CỬA HÀNG",pink,ShowHome,32);UIFactory.Anchor(title.GetComponent<RectTransform>(),new Vector2(.5f,1),new Vector2(0,-58),new Vector2(650,92));shopCoins=UIFactory.Text("Coins",shop.transform,"₫ 0",28,TextAnchor.MiddleRight);UIFactory.Anchor(shopCoins.rectTransform,new Vector2(1,1),new Vector2(-55,-120),new Vector2(250,60));
            var scroll=UIFactory.Go("Scroll",shop.transform);var sr=scroll.AddComponent<RectTransform>();UIFactory.Anchor(sr,new Vector2(.5f,.5f),new Vector2(0,-40),new Vector2(650,980));var sc=scroll.AddComponent<ScrollRect>();sc.horizontal=false;var vp=UIFactory.Go("Viewport",scroll.transform);UIFactory.Stretch(vp);vp.AddComponent<Image>().color=new Color(.08f,.03f,.13f,.28f);vp.AddComponent<Mask>().showMaskGraphic=false;sc.viewport=vp.GetComponent<RectTransform>();var content=UIFactory.Go("Content",vp.transform);var cr=content.AddComponent<RectTransform>();cr.anchorMin=new Vector2(0,1);cr.anchorMax=new Vector2(1,1);cr.pivot=new Vector2(.5f,1);cr.sizeDelta=new Vector2(0,2300);var v=content.AddComponent<VerticalLayoutGroup>();v.padding=new RectOffset(14,14,14,14);v.spacing=14;v.childForceExpandHeight=false;v.childControlHeight=false;shopContent=content.transform;sc.content=cr;
        }
        void BuildCharacter(){
            character=Screen("Character",SpriteCatalog.Home());var back=UIFactory.Button("Back",character.transform,"‹  NHÂN VẬT",purple,ShowHome,30);UIFactory.Anchor(back.GetComponent<RectTransform>(),new Vector2(.5f,1),new Vector2(0,-58),new Vector2(650,92));
            var card=UIFactory.Go("Card",character.transform);var cr=card.AddComponent<RectTransform>();UIFactory.Anchor(cr,new Vector2(.5f,.5f),new Vector2(0,55),new Vector2(620,820));UIFactory.Panel3D(card,new Color(.28f,.07f,.36f,.88f));var mi=UIFactory.Image("Mai",card.transform,Color.white,SpriteCatalog.Mascot());UIFactory.Rect(mi.gameObject,new Vector2(0,0.20f),new Vector2(1,1),new Vector2(40,15),new Vector2(-40,-25));mi.preserveAspect=true;charMascot=mi.gameObject.AddComponent<MascotMotion>();var b=mi.gameObject.AddComponent<Button>();b.targetGraphic=mi;b.onClick.AddListener(()=>{charMascot.Cheer();AudioHaptics.Vibrate(14);});
            friendshipText=UIFactory.Text("Friendship",card.transform,"TÌNH BẠN 0/100",26);UIFactory.Rect(friendshipText.gameObject,new Vector2(0,0),new Vector2(1,.18f),new Vector2(18,20),new Vector2(-18,-10));
            var cosmetics=UIFactory.Go("Cosmetics",character.transform);var rr=cosmetics.AddComponent<RectTransform>();UIFactory.Anchor(rr,new Vector2(.5f,0),new Vector2(0,100),new Vector2(620,120));var gl=cosmetics.AddComponent<GridLayoutGroup>();gl.constraint=GridLayoutGroup.Constraint.FixedColumnCount;gl.constraintCount=2;gl.cellSize=new Vector2(295,110);gl.spacing=new Vector2(18,0);UIFactory.Button("Lotus",cosmetics.transform,"HÀO QUANG SEN",pink,()=>EquipCosmetic("lotus"),19);UIFactory.Button("Gold",cosmetics.transform,"KHUNG VÀNG 3D",gold,()=>EquipCosmetic("gold"),19);
        }
        void BuildEvents(){
            events=Screen("Events",SpriteCatalog.Get("Art/Events/event-festival"));var back=UIFactory.Button("Back",events.transform,"‹  SỰ KIỆN",pink,ShowHome,32);UIFactory.Anchor(back.GetComponent<RectTransform>(),new Vector2(.5f,1),new Vector2(0,-58),new Vector2(650,92));
            var scroll=UIFactory.Go("Scroll",events.transform);var sr=scroll.AddComponent<RectTransform>();UIFactory.Anchor(sr,new Vector2(.5f,.5f),new Vector2(0,-45),new Vector2(650,1010));var sc=scroll.AddComponent<ScrollRect>();sc.horizontal=false;var vp=UIFactory.Go("Viewport",scroll.transform);UIFactory.Stretch(vp);vp.AddComponent<Image>().color=new Color(.08f,.03f,.13f,.30f);vp.AddComponent<Mask>().showMaskGraphic=false;sc.viewport=vp.GetComponent<RectTransform>();var content=UIFactory.Go("Content",vp.transform);var cr=content.AddComponent<RectTransform>();cr.anchorMin=new Vector2(0,1);cr.anchorMax=new Vector2(1,1);cr.pivot=new Vector2(.5f,1);cr.sizeDelta=new Vector2(0,1600);var vg=content.AddComponent<VerticalLayoutGroup>();vg.padding=new RectOffset(14,14,14,14);vg.spacing=14;vg.childControlHeight=false;vg.childForceExpandHeight=false;eventsContent=content.transform;sc.content=cr;
        }
        void BuildSettings(){
            settings=Screen("Settings",SpriteCatalog.Home());var panel=UIFactory.Go("Panel",settings.transform);var pr=panel.AddComponent<RectTransform>();UIFactory.Anchor(pr,new Vector2(.5f,.5f),Vector2.zero,new Vector2(620,820));UIFactory.Panel3D(panel,new Color(.22f,.05f,.33f,.95f));var title=UIFactory.Text("Title",panel.transform,"CÀI ĐẶT",38);UIFactory.Rect(title.gameObject,new Vector2(0,.84f),Vector2.one,new Vector2(10,0),new Vector2(-10,0));
            var smooth=UIFactory.Button("Smooth",panel.transform,"MƯỢT",cyan,()=>SetQuality(QualityMode.Smooth),25);UIFactory.Anchor(smooth.GetComponent<RectTransform>(),new Vector2(.5f,.70f),Vector2.zero,new Vector2(500,90));var auto=UIFactory.Button("Auto",panel.transform,"AUTO",purple2,()=>SetQuality(QualityMode.Auto),25);UIFactory.Anchor(auto.GetComponent<RectTransform>(),new Vector2(.5f,.55f),Vector2.zero,new Vector2(500,90));var max=UIFactory.Button("Max",panel.transform,"3D MAX",pink,()=>SetQuality(QualityMode.Max3D),25);UIFactory.Anchor(max.GetComponent<RectTransform>(),new Vector2(.5f,.40f),Vector2.zero,new Vector2(500,90));var hap=UIFactory.Button("Haptic",panel.transform,"BẬT/TẮT RUNG",gold,ToggleHaptic,24);UIFactory.Anchor(hap.GetComponent<RectTransform>(),new Vector2(.5f,.25f),Vector2.zero,new Vector2(500,90));var close=UIFactory.Button("Close",panel.transform,"ĐÓNG",green,ShowHome,25);UIFactory.Anchor(close.GetComponent<RectTransform>(),new Vector2(.5f,.09f),Vector2.zero,new Vector2(500,90));
        }
        void BuildModal(){
            modal=UIFactory.Go("Modal",safe.transform);UIFactory.Stretch(modal);modal.AddComponent<Image>().color=new Color(0,0,0,.68f);var card=UIFactory.Go("Card",modal.transform);var cr=card.AddComponent<RectTransform>();UIFactory.Anchor(cr,new Vector2(.5f,.5f),Vector2.zero,new Vector2(620,760));UIFactory.Panel3D(card,new Color(.98f,.91f,.75f,.99f));modalTitle=UIFactory.Text("Title",card.transform,"",38,TextAnchor.MiddleCenter,new Color(.36f,.08f,.42f));UIFactory.Rect(modalTitle.gameObject,new Vector2(0,.78f),Vector2.one,new Vector2(20,0),new Vector2(-20,0));modalBody=UIFactory.Text("Body",card.transform,"",24,TextAnchor.MiddleCenter,new Color(.20f,.08f,.24f));UIFactory.Rect(modalBody.gameObject,new Vector2(0,.27f),new Vector2(1,.80f),new Vector2(28,10),new Vector2(-28,-10));modalButtons=UIFactory.Go("Buttons",card.transform).transform;UIFactory.Rect(modalButtons.gameObject,new Vector2(0,0),new Vector2(1,.28f),new Vector2(28,20),new Vector2(-28,-10));var vg=modalButtons.gameObject.AddComponent<VerticalLayoutGroup>();vg.spacing=10;vg.childForceExpandHeight=true;vg.childForceExpandWidth=true;modal.SetActive(false);
        }
        void BuildToast(){toastGo=UIFactory.Go("Toast",safe.transform);var rt=toastGo.AddComponent<RectTransform>();UIFactory.Anchor(rt,new Vector2(.5f,.18f),Vector2.zero,new Vector2(560,72));UIFactory.Panel3D(toastGo,new Color(.15f,.04f,.22f,.94f));toastText=UIFactory.Text("Text",toastGo.transform,"",22);UIFactory.Stretch(toastText.gameObject,10,5,10,5);toastGo.SetActive(false);}
        public void ShowHome(){ShowOnly(home);RefreshHome();}
        public void RefreshHome(){homeHearts.text=$"♥  {save.Data.hearts}  ĐẦY";homeCoins.text=$"₫  {save.Data.coins:N0}";homeLevel.text=$"MÀN {save.Data.unlocked}";}
        void ShowOnly(GameObject screen){foreach(var s in new[]{home,map,gameScreen,shop,character,events,settings})if(s)s.SetActive(s==screen);modal.SetActive(false);}
        public void ShowMap(){ShowOnly(map);RebuildMap();}
        void RebuildMap(){foreach(Transform c in mapContent)Destroy(c.gameObject);int currentRegion=(save.Data.unlocked-1)/10;mapBackground.sprite=SpriteCatalog.Region(currentRegion);for(int i=1;i<=50;i++){int level=i;bool unlocked=i<=save.Data.unlocked;string stars=new string('★',save.Data.stars[i-1])+new string('☆',3-save.Data.stars[i-1]);var b=UIFactory.Button("L"+i,mapContent,$"{i}\n{stars}",unlocked?green:new Color(.26f,.26f,.32f,.9f),()=>{if(unlocked)game.StartLevel(level);},21);b.interactable=unlocked;}}
        public void ShowShop(){ShowOnly(shop);RebuildShop();}
        class ShopItem {public string id,name,desc;public int price;public Action reward;}
        void RebuildShop(){foreach(Transform c in shopContent)Destroy(c.gameObject);shopCoins.text=$"₫ {save.Data.coins:N0}";var items=BuildShopItems();int deal=(DateTime.Now.DayOfYear+DateTime.Now.Year)%items.Count;for(int i=0;i<items.Count;i++){var item=items[i];int price=i==deal?Mathf.RoundToInt(item.price*.7f):item.price;var card=UIFactory.Go(item.id,shopContent);var rt=card.AddComponent<RectTransform>();rt.sizeDelta=new Vector2(0,150);UIFactory.Panel3D(card,new Color(.99f,.93f,.78f,.98f));var txt=UIFactory.Text("Info",card.transform,$"{item.name}\n{item.desc}{(i==deal?"   - DEAL -30%":"")}",21,TextAnchor.MiddleLeft,new Color(.28f,.08f,.33f));UIFactory.Rect(txt.gameObject,Vector2.zero,new Vector2(.67f,1),new Vector2(20,10),new Vector2(-8,-10));var buy=UIFactory.Button("Buy",card.transform,$"₫ {price:N0}",green,()=>Buy(item,price),21);UIFactory.Rect(buy.gameObject,new Vector2(.69f,.18f),new Vector2(.98f,.82f),Vector2.zero,Vector2.zero);}
            var gift=UIFactory.Button("DailyGift",shopContent,"QUÀ MIỄN PHÍ HẰNG NGÀY",pink,ClaimShopGift,25);gift.GetComponent<RectTransform>().sizeDelta=new Vector2(0,110);
        }
        List<ShopItem> BuildShopItems()=>new(){
            new(){id="basket",name="Giỏ tre",desc="Xóa nhanh 1 mục tiêu",price=500,reward=()=>save.Data.inventory.basket++},
            new(){id="fan",name="Quạt gió",desc="Quét sạch một hàng",price=800,reward=()=>save.Data.inventory.fan++},
            new(){id="pinwheel",name="Chong chóng",desc="Xáo bàn và tạo cơ hội",price=1000,reward=()=>save.Data.inventory.pinwheel++},
            new(){id="moves",name="Vé +5 lượt",desc="Cứu màn khi hết lượt",price=1500,reward=()=>save.Data.inventory.extraMoves++},
            new(){id="heart",name="Hồi đầy tim",desc="Trở lại hành trình ngay",price=600,reward=()=>save.Data.hearts=5},
            new(){id="starter",name="Gói Khởi Đầu",desc="Mỗi trợ lực +2",price=2200,reward=()=>{save.Data.inventory.basket+=2;save.Data.inventory.fan+=2;save.Data.inventory.pinwheel+=2;}},
            new(){id="deluxe",name="Gói Deluxe",desc="Mỗi trợ lực +4 và +1 vé",price=4200,reward=()=>{save.Data.inventory.basket+=4;save.Data.inventory.fan+=4;save.Data.inventory.pinwheel+=4;save.Data.inventory.extraMoves++;}},
            new(){id="lotus",name="Hào quang Sen",desc="Trang trí cho Mai",price=1500,reward=()=>save.Data.lotusOwned=true},
            new(){id="gold",name="Khung Vàng 3D",desc="Khung nhân vật cao cấp",price=1900,reward=()=>save.Data.goldOwned=true},
            new(){id="festival",name="Gói Lễ Hội",desc="+3 mỗi trợ lực +2 vé",price=2800,reward=()=>{save.Data.inventory.basket+=3;save.Data.inventory.fan+=3;save.Data.inventory.pinwheel+=3;save.Data.inventory.extraMoves+=2;}},
            new(){id="chest",name="Rương Vàng",desc="500 xu + 1 trợ lực",price=2000,reward=()=>{save.Data.coins+=500;save.Data.inventory.basket++;}},
            new(){id="master",name="Kho báu Vườn Việt",desc="+10 mỗi trợ lực +3 vé",price=4900,reward=()=>{save.Data.inventory.basket+=10;save.Data.inventory.fan+=10;save.Data.inventory.pinwheel+=10;save.Data.inventory.extraMoves+=3;}}
        };
        void Buy(ShopItem item,int price){if(!save.SpendCoins(price)){Toast("Không đủ xu");AudioHaptics.Vibrate(35);return;}item.reward();save.Save();sfx.Play("special");shopCoins.text=$"₫ {save.Data.coins:N0}";Toast("Đã mua "+item.name);AudioHaptics.Vibrate(16);fx.Flash(new Color(1f,.75f,.2f));RebuildShop();}
        void ClaimShopGift(){string day=DateTime.Now.ToString("yyyy-MM-dd");if(save.Data.dailyGift==day){Toast("Hôm nay đã nhận quà");return;}save.Data.dailyGift=day;save.Data.coins+=150;save.Data.inventory.basket++;save.Save();Toast("Nhận 150 xu + 1 Giỏ tre!");RebuildShop();}
        public void ShowCharacter(){ShowOnly(character);friendshipText.text=$"TÌNH BẠN  {save.Data.friendship}/100\nChạm vào Mai để tương tác";}
        void EquipCosmetic(string id){bool owned=id=="lotus"?save.Data.lotusOwned:save.Data.goldOwned;if(!owned){Toast("Mua vật phẩm này trong Cửa hàng trước");return;}save.Data.activeCosmetic=save.Data.activeCosmetic==id?"":id;save.Save();Toast(save.Data.activeCosmetic==id?"Đã trang bị":"Đã tháo trang bị");charMascot.Cheer();}
        public void ShowEvents(){ShowOnly(events);RebuildEvents();}
        void RebuildEvents(){
            foreach(Transform c in eventsContent)Destroy(c.gameObject);var e=eventSystem.Data;
            EventCard($"LỄ HỘI TRÁI CÂY  {Mathf.Min(350,e.festivalPoints)}/350","Hoàn thành nhiệm vụ và màn chơi để mở các mốc thưởng",null,pink);
            EventCard($"ĐIỂM DANH 7 NGÀY - Chuỗi {e.dailyStreak}/7","Quà xu tăng dần; ngày 4/6/7 có thêm trợ lực",()=>{eventSystem.ClaimDaily(out var m);Toast(m);save.RefreshHearts();RefreshHome();RebuildEvents();},gold);
            EventCard(eventSystem.ChestLabel(),"150 xu + 1 trợ lực, hồi sau 4 giờ",()=>{eventSystem.ClaimChest(out var m);Toast(m);RebuildEvents();},cyan);
            EventCard($"NHIỆM VỤ: Chơi 3 màn  {e.missionPlayed}/3","Thưởng 120 xu",()=>{eventSystem.ClaimMission("played",out var m);Toast(m);RebuildEvents();},green);
            EventCard($"NHIỆM VỤ: Thắng 1 màn  {e.missionWins}/1","Thưởng 180 xu",()=>{eventSystem.ClaimMission("wins",out var m);Toast(m);RebuildEvents();},green);
            EventCard($"NHIỆM VỤ: Tạo 3 special  {e.missionSpecials}/3","Thưởng 1 Chong chóng",()=>{eventSystem.ClaimMission("specials",out var m);Toast(m);RebuildEvents();},green);
            var milestones=eventSystem.MilestoneValues();for(int i=0;i<milestones.Length;i++){int idx=i;EventCard($"MỐC LỄ HỘI {milestones[i]} ĐIỂM",e.milestoneClaims[i]?"ĐÃ NHẬN":"Chạm để nhận khi đủ điểm",()=>{eventSystem.ClaimMilestone(idx,out var m);Toast(m);RebuildEvents();},purple2);}
        }
        void EventCard(string title,string desc,Action action,Color color){var card=UIFactory.Go("EventItem",eventsContent);var rt=card.AddComponent<RectTransform>();rt.sizeDelta=new Vector2(0,128);UIFactory.Panel3D(card,new Color(.98f,.92f,.78f,.97f));var tx=UIFactory.Text("Info",card.transform,title+"\n"+desc,21,TextAnchor.MiddleLeft,new Color(.28f,.08f,.34f));UIFactory.Rect(tx.gameObject,Vector2.zero,new Vector2(action==null?1:.70f,1),new Vector2(18,8),new Vector2(-10,-8));if(action!=null){var b=UIFactory.Button("Claim",card.transform,"NHẬN",color,action,20);UIFactory.Rect(b.gameObject,new Vector2(.72f,.20f),new Vector2(.98f,.80f),Vector2.zero,Vector2.zero);}}

        public void ShowSettings(){ShowOnly(settings);}
        void SetQuality(QualityMode q){save.Data.quality=q;save.Save();fx.Quality=q;Toast("Đồ họa: "+(q==QualityMode.Max3D?"3D MAX":q==QualityMode.Smooth?"MƯỢT":"AUTO"));}
        void ToggleHaptic(){save.Data.haptic=!save.Data.haptic;save.Save();AudioHaptics.HapticsEnabled=save.Data.haptic;Toast(save.Data.haptic?"Đã bật rung":"Đã tắt rung");}
        public void ShowGame(){ShowOnly(gameScreen);}
        public TileView[] Tiles=>tileViews;
        public void UpdateGame(LevelDefinition level,int score,int moves,Dictionary<int,int> goals,int jelly,int fever){gameLevel.text=$"MÀN {level.id}";gameScore.text=$"{score:N0}";gameMoves.text=$"{moves} LƯỢT";string g="MỤC TIÊU  ";foreach(var kv in goals)g+=$"🍊{kv.Value}  ";if(jelly>0)g+=$"💧{jelly}";gameGoals.text=g;gameFever.text=$"NĂNG LƯỢNG VƯỜN {fever}%";}
        public void RenderTiles(TileData[] data,bool[] jellies,int selected,QualityMode q){for(int i=0;i<tileViews.Length;i++){if(data[i]!=null)data[i].jelly=jellies[i];tileViews[i].Set(data[i],i==selected,q);}}
        public void ShowTutorial(int step){if(step<=0)return;string[] copy={"","Vuốt hoặc chạm 2 trái cây cạnh nhau để ghép 3.","Mục tiêu rất nhẹ — hãy làm quen với combo.","Ghép 4 tạo TÊN LỬA.","Jelly xuất hiện: ghép trên ô sáng để xóa.","Bạn được tặng sẵn một vật phẩm đặc biệt."};ShowModal("HƯỚNG DẪN",copy[Mathf.Clamp(step,1,5)],new[]{("BẮT ĐẦU",(Action)(()=>HideModal()))});}
        public void ShowResult(bool won,int level,int stars,int score,int coins,Action next,Action retry){if(won){homeMascot?.Cheer();ShowModal("HOÀN THÀNH!",$"Màn {level}\n{new string('★',stars)}{new string('☆',3-stars)}\n\n{score:N0} điểm\n+{coins} xu",new[]{("MÀN TIẾP THEO",next),("VỀ BẢN ĐỒ",(Action)ShowMap)});}else{var acts=new List<(string,Action)>{("CHƠI LẠI",retry)};if(save.Data.inventory.extraMoves>0)acts.Insert(0,("DÙNG +5 LƯỢT",()=>game.UseExtraMoves()));acts.Add(("CỬA HÀNG",ShowShop));ShowModal("SUÝT NỮA RỒI!","Mai đang cổ vũ bạn. Dùng trợ lực hoặc thử lại nhé.",acts.ToArray());}}
        public void ShowPause()=>ShowModal("TẠM DỪNG","Tiến trình màn hiện tại vẫn được giữ.",new[]{("TIẾP TỤC",(Action)HideModal),("VỀ TRANG CHÍNH",(Action)ShowHome)});
        public void ShowModal(string title,string body,(string,Action)[] actions){modalTitle.text=title;modalBody.text=body;foreach(Transform c in modalButtons)Destroy(c.gameObject);foreach(var a in actions){var b=UIFactory.Button("Action",modalButtons,a.Item1,a.Item1.Contains("CỬA")?cyan:green,()=>{HideModal();a.Item2?.Invoke();},23);b.GetComponent<RectTransform>().sizeDelta=new Vector2(0,78);}modal.SetActive(true);}
        public void HideModal()=>modal.SetActive(false);
        public void Toast(string message){StopCoroutine(nameof(ToastRoutine));StartCoroutine(ToastRoutine(message));}
        IEnumerator ToastRoutine(string m){toastText.text=m;toastGo.SetActive(true);yield return new WaitForSecondsRealtime(1.5f);toastGo.SetActive(false);}
    }
}
